/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { getDefaultContent } from "./top-nav-bar.content";

// Header component with applied rules
function TopNavBar(props) {
  let navigation;
  if (!props.content) {
    navigation = getDefaultContent();
  } else {
    navigation = props.content;
  }

  console.log("TopNavBar content:", navigation);

  return (
    <div className="hidden lg:flex gap-5 justify-between px-6 py-2 text-center text-white uppercase bg-neutral-700 max-md:flex-wrap max-md:pr-5">
      {navigation?.group[0]?.level1.map((item, index) => (
        <nav
          key={index}
          className="justify-center py-2 px-4 text-base leading-6 whitespace-nowrap rounded-md border-2 border-solid border-stone-950"
        >
          <a href={item.src} key={index}>
            {item.text}
          </a>
        </nav>
      ))}

      <div className="flex gap-5 justify-between my-auto text-sm leading-5 max-md:flex-wrap max-md:max-w-full">
        {navigation.group[1].level1.map((item, index) => (
          <nav
            key={index}
            tabIndex="0"
            className="flex-auto text-sm leading-5 whitespace-nowrap cursor-pointer"
          >
            <a href={item.src}>{item.text}</a>
          </nav>
        ))}
      </div>
    </div>
  );
}

export default TopNavBar;
