/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface HospitalInfo {
  imgSrc: string;
  imgAlt: string;
  name: string;
}

const hospitalData: HospitalInfo[] = [
  { imgSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/3900d74ee8a128c3c930fbc58c3f547decdb0e19c852f6a64a87775f6078d2bf?apiKey=9d9c17771b684627bed7d61d5f05ef44&", imgAlt: "Orlando Health Arnold Palmer Hospital for Children", name: "Orlando Health Arnold Palmer Hospital for Children" },
  { imgSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/379061e4da77ab88600bc6811fbebd738e2479530e06784fad3880becbbd8d82?apiKey=9d9c17771b684627bed7d61d5f05ef44&", imgAlt: "Orlando Health South Lake Hospital Emergency Services", name: "Orlando Health South Lake Hospital Emergency Services" },
  { imgSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/0fb11491a0b59738fbca5f95b78ad948f169c0549a63b0c7e508b551e391cd9c?apiKey=9d9c17771b684627bed7d61d5f05ef44&", imgAlt: "Orlando Health Emergency Room and Medical Pavilion – Four Corners", name: "Orlando Health Emergency Room and Medical Pavilion – Four Corners" },
  
  { imgSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/64e34304e9f1fed4e79aa389e841e7544704624daa1fea7329a754843c048727?apiKey=9d9c17771b684627bed7d61d5f05ef44&", imgAlt: "Orlando Health Dr. P. Phillips Hospital", name: "Orlando Health Dr. P. Phillips Hospital" },
  { imgSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/34a5dd377565c2cafd51b2e8a116bfe887b22e8c3ae34a72eee21ba476940d48?apiKey=9d9c17771b684627bed7d61d5f05ef44&", imgAlt: "Orlando Health — Health Central Hospital", name: "Orlando Health — Health Central Hospital" },
  { imgSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/2fa228b01351d7e3dd32d2e047ee1ffef1c3a2bcf3151e28b4010b57b4fe903b?apiKey=9d9c17771b684627bed7d61d5f05ef44&", imgAlt: "Orlando Health Horizon West Hospital", name: "Orlando Health Horizon West Hospital" },
  { imgSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/6df86d35f7ce1af3bc623a44fff6ee2afb2d9522f246856a682a42dbe9b2eaa3?apiKey=9d9c17771b684627bed7d61d5f05ef44&", imgAlt: "Orlando Health Emergency Room and Medical Pavilion – Osceola", name: "Orlando Health Emergency Room and Medical Pavilion – Osceola" },
  
  { imgSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/5a498906196da2668d4a993ab10784834f6533fe0f1ad21d71362dc452dbff52?apiKey=9d9c17771b684627bed7d61d5f05ef44&", imgAlt: "Orlando Health Emergency Room and Medical Pavilion – Lake Mary", name: "Orlando Health Emergency Room and Medical Pavilion – Lake Mary" },
  { imgSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/8fb83d32c1aaa169c120b1e0fcdc5703948d100a17af2abdb565ac1f7e3ce574?apiKey=9d9c17771b684627bed7d61d5f05ef44&", imgAlt: "Orlando Health Emergency Room and Medical Pavilion – Blue Cedar", name: "Orlando Health Emergency Room and Medical Pavilion – Blue Cedar" },
  { imgSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/23fe3edcbecc8325d866fb813271270496a5161a6685609d4f621d856eedfde5?apiKey=9d9c17771b684627bed7d61d5f05ef44&", imgAlt: "Orlando Health South Seminole Hospital", name: "Orlando Health South Seminole Hospital" },
  
  { imgSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/e690ad97d0ea07b816378e0721fd8b40f47eaef5114d93b21eca8cee96dbfe7e?apiKey=9d9c17771b684627bed7d61d5f05ef44&", imgAlt: "Orlando Health Orlando Regional Medical Center", name: "Orlando Health Orlando Regional Medical Center" },
  { imgSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/0330f24d455c43e52c449b49f256140dd484a3e28ad6696c643beee719102dee?apiKey=9d9c17771b684627bed7d61d5f05ef44&", imgAlt: "Orlando Health Emergency Room – Randal Park", name: "Orlando Health Emergency Room – Randal Park" },
  { imgSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/cd3a3cb26519aff9aa2b53decf60a1f13930cd33836e0978acdf52da52c19d9e?apiKey=9d9c17771b684627bed7d61d5f05ef44&", imgAlt: "Orlando Health Emergency Room – Reunion Village", name: "Orlando Health Emergency Room – Reunion Village" },
  { imgSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/a75219bdc6ddc51c4d2c8d0530c2b5825961fabcb9a5688d671936e676886ec2?apiKey=9d9c17771b684627bed7d61d5f05ef44&", imgAlt: "Orlando Health St. Cloud Hospital", name: "Orlando Health St. Cloud Hospital" },
];

const HospitalListing: React.FC<HospitalInfo> = ({ imgSrc, imgAlt, name }) => (
  <div className="flex gap-4">
    <img loading="lazy" src={imgSrc} className="shrink-0 self-start aspect-[0.59] w-[13px]" alt={imgAlt} />
    <div>{name}</div>
  </div>
);

const HealthcareInfoSection: React.FC = () => (
  <section className="flex justify-center items-center px-16 pt-12 pb-20 bg-neutral-700 md:px-5">
    <div className="flex flex-col max-w-full w-[1152px]">
      <header className="text-4xl font-medium leading-10 text-white md:max-w-full">
        Central Florida’s Leader in Emergency and Trauma Care
      </header>
      <p className="mt-10 text-lg leading-7 text-white md:max-w-full">
        Emergencies can’t wait, and Orlando Health's ERs are ready. Don't delay your care–we're here when you need us.
      </p>
      <div className="mt-14 md:pr-5 md:mt-10 md:max-w-full">
        <nav className="flex gap-5 md:flex-col md:gap-0">
          {hospitalData.map((hospital, index) => (
            <div key={index} className={`flex flex-col w-3/12 md:ml-0 md:w-full ${index !== 0 ? "ml-5 mt-0" : ""} md:mt-10`}>
              <HospitalListing {...hospital} />
            </div>
          ))}
        </nav>
      </div>
    </div>
  </section>
);

export default HealthcareInfoSection;