/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ImageWithTextProps {
  imgUrl: string;
  alt: string;
  headerText: string;
  paragraphText: string;
}

const ImageWithText: React.FC<ImageWithTextProps> = ({
  imgUrl,
  alt,
  headerText,
  paragraphText,
}) => {
  return (
    <section className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
      <img
        loading="lazy"
        src={imgUrl}
        alt={alt}
        className="grow w-full aspect-[1.32] max-md:mt-8 max-md:max-w-full"
      />
      <div className="flex flex-col self-stretch px-5 my-auto text-neutral-700 max-md:mt-10 max-md:max-w-full">
        <h2 className="text-4xl leading-10 max-md:max-w-full">{headerText}</h2>
        <p className="mt-7 text-lg leading-7 max-md:max-w-full">{paragraphText}</p>
        <button
          type="button"
          className="justify-center self-start px-8 py-3.5 mt-9 text-base font-semibold leading-4 text-white bg-orange-700 rounded-3xl max-md:px-5 max-md:max-w-full"
        >
          See Careers
        </button>
      </div>
    </section>
  );
};

const CareerOpportunities: React.FC = () => {
  const content = [
    {
      imgUrl: "https://cdn.builder.io/api/v1/image/assets/TEMP/71c79116e517edc5f905df5c0353bdae67f640181698393b6d4b6d8eb8b346f7?apiKey=9d9c17771b684627bed7d61d5f05ef44&",
      alt: "Career opportunity at Orlando Health",
      headerText: "Careers at Orlando Health",
      paragraphText:
        "Join a team that serves your community. Both clinical and non-clinical opportunities are available now.",
    },
  ];

  return (
    <main className="justify-center bg-gray-200">
      <div className="flex gap-5 max-md:flex-col max-md:gap-0">
        {content.map((item, index) => (
          <ImageWithText
            key={index}
            imgUrl={item.imgUrl}
            alt={item.alt}
            headerText={item.headerText}
            paragraphText={item.paragraphText}
          />
        ))}
      </div>
    </main>
  );
};

export default CareerOpportunities;